name: 'Build and push'
description: 'Build a docker image then push it to Docker'
inputs:

  username:
    description: 'Username to use to authenticate with image registry'
    required: true
  token:
    description: 'Token to use to authenticate with the image registry'
    required: true

  context:
    description: 'Docker build command context'
    required: false
    default: ${{github.workspace}}
  file:
    description: 'Docker file path'
    required: true
  tag:
    description: 'The tag for the docker image'
    required: true
  build-args:
    description: 'Docker build args'
    required: false

runs:
  using: composite
  steps:
    - name: Setup Docker buildX
      uses: docker/setup-buildx-action@v1

    - name: Login to images hub
      uses: docker/login-action@v1
      with:
        username: ${{inputs.username}}
        password: ${{inputs.token}}

    - name: Build and push the image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ${{inputs.context}}
        file: ${{inputs.file}}
        push: true
        tags: ${{ inputs.tags }}
        build-args: ${{ inputs.build-args }}