version: "3.8"
services:
  lavapp:
    image: mimidots/php7.4:1.0.0-alpine
    volumes:
      - $PWD/site:/var/www/html/site
    restart: on-failure
    ports:
      - "9000"
    healthcheck:
      test: [ "CMD","ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - demolav #place them on same network to allow us to call it by the service name

  server:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - $PWD/nginx.conf:/etc/nginx/conf.d/default.conf
      - $PWD/site:/var/www/html/site/
    depends_on:
      - lavapp
    networks:
      - demolav

networks:
  demolav:
    name: demolav
    driver: bridge