version: "3.8"

services:
  app:
    image: ${IMAGE?err}
    volumes:
      - $PWD/site:/var/www/html
    restart: on-failure
    ports:
      - "9000"
    healthcheck:
      test: [ "CMD","ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - phpdemo

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - $PWD/nginx.conf:/etc/nginx/conf.d/default.conf
      - $PWD/site:/var/www/html/
    depends_on:
      - app
    networks:
      - phpdemo

networks:
  phpdemo:
    driver: bridge